apiDir: ../analytics-graphql-rest-api/src/main/java
apiPackagePath: com.liferay.analytics.graphql.rest
application:
    baseURI: /analytics-graphql-rest
    className: AnalyticsGraphQLRESTApplication
    name: Liferay.Analytics.GraphQL.REST
author: Ivica Cardic
clientDir: ../analytics-graphql-rest-client/src/main/java
compatibilityVersion: 15
forcePredictableOperationId: true
generateBatch: false
generateGraphQL: false
javaEEPackage: jakarta
testDir: ../analytics-graphql-rest-test/src/testIntegration/java