/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.batch.engine.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.batch.engine.model.BatchJob;
import com.liferay.batch.engine.model.BatchJobModel;
import com.liferay.batch.engine.model.BatchJobSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BatchJob service. Represents a row in the &quot;BatchJob&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>BatchJobModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BatchJobImpl}.
 * </p>
 *
 * @author Matija Petanjek
 * @see BatchJobImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class BatchJobModelImpl
	extends BaseModelImpl<BatchJob> implements BatchJobModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a batch job model instance should use the <code>BatchJob</code> interface instead.
	 */
	public static final String TABLE_NAME = "BatchJob";

	public static final Object[][] TABLE_COLUMNS = {
		{"batchJobId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"key_", Types.VARCHAR},
		{"name", Types.VARCHAR}, {"startTime", Types.TIMESTAMP},
		{"endTime", Types.TIMESTAMP}, {"status", Types.VARCHAR},
		{"callbackURL", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("batchJobId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("key_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("callbackURL", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BatchJob (batchJobId LONG not null primary key,createDate DATE null,modifiedDate DATE null,key_ VARCHAR(75) null,name VARCHAR(75) null,startTime DATE null,endTime DATE null,status VARCHAR(75) null,callbackURL VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table BatchJob";

	public static final String ORDER_BY_JPQL =
		" ORDER BY batchJob.batchJobId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BatchJob.batchJobId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.batch.engine.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.batch.engine.model.BatchJob"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.batch.engine.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.batch.engine.model.BatchJob"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.batch.engine.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.batch.engine.model.BatchJob"),
		true);

	public static final long KEY_COLUMN_BITMASK = 1L;

	public static final long BATCHJOBID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BatchJob toModel(BatchJobSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BatchJob model = new BatchJobImpl();

		model.setBatchJobId(soapModel.getBatchJobId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setKey(soapModel.getKey());
		model.setName(soapModel.getName());
		model.setStartTime(soapModel.getStartTime());
		model.setEndTime(soapModel.getEndTime());
		model.setStatus(soapModel.getStatus());
		model.setCallbackURL(soapModel.getCallbackURL());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BatchJob> toModels(BatchJobSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BatchJob> models = new ArrayList<BatchJob>(soapModels.length);

		for (BatchJobSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.batch.engine.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.batch.engine.model.BatchJob"));

	public BatchJobModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _batchJobId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBatchJobId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _batchJobId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BatchJob.class;
	}

	@Override
	public String getModelClassName() {
		return BatchJob.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BatchJob, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BatchJob, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BatchJob, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((BatchJob)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BatchJob, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BatchJob, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BatchJob)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BatchJob, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BatchJob, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<BatchJob, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<BatchJob, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<BatchJob, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<BatchJob, Object>>();
		Map<String, BiConsumer<BatchJob, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<BatchJob, ?>>();

		attributeGetterFunctions.put(
			"batchJobId",
			new Function<BatchJob, Object>() {

				@Override
				public Object apply(BatchJob batchJob) {
					return batchJob.getBatchJobId();
				}

			});
		attributeSetterBiConsumers.put(
			"batchJobId",
			new BiConsumer<BatchJob, Object>() {

				@Override
				public void accept(BatchJob batchJob, Object batchJobId) {
					batchJob.setBatchJobId((Long)batchJobId);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<BatchJob, Object>() {

				@Override
				public Object apply(BatchJob batchJob) {
					return batchJob.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<BatchJob, Object>() {

				@Override
				public void accept(BatchJob batchJob, Object createDate) {
					batchJob.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<BatchJob, Object>() {

				@Override
				public Object apply(BatchJob batchJob) {
					return batchJob.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<BatchJob, Object>() {

				@Override
				public void accept(BatchJob batchJob, Object modifiedDate) {
					batchJob.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"key",
			new Function<BatchJob, Object>() {

				@Override
				public Object apply(BatchJob batchJob) {
					return batchJob.getKey();
				}

			});
		attributeSetterBiConsumers.put(
			"key",
			new BiConsumer<BatchJob, Object>() {

				@Override
				public void accept(BatchJob batchJob, Object key) {
					batchJob.setKey((String)key);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<BatchJob, Object>() {

				@Override
				public Object apply(BatchJob batchJob) {
					return batchJob.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<BatchJob, Object>() {

				@Override
				public void accept(BatchJob batchJob, Object name) {
					batchJob.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"startTime",
			new Function<BatchJob, Object>() {

				@Override
				public Object apply(BatchJob batchJob) {
					return batchJob.getStartTime();
				}

			});
		attributeSetterBiConsumers.put(
			"startTime",
			new BiConsumer<BatchJob, Object>() {

				@Override
				public void accept(BatchJob batchJob, Object startTime) {
					batchJob.setStartTime((Date)startTime);
				}

			});
		attributeGetterFunctions.put(
			"endTime",
			new Function<BatchJob, Object>() {

				@Override
				public Object apply(BatchJob batchJob) {
					return batchJob.getEndTime();
				}

			});
		attributeSetterBiConsumers.put(
			"endTime",
			new BiConsumer<BatchJob, Object>() {

				@Override
				public void accept(BatchJob batchJob, Object endTime) {
					batchJob.setEndTime((Date)endTime);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<BatchJob, Object>() {

				@Override
				public Object apply(BatchJob batchJob) {
					return batchJob.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<BatchJob, Object>() {

				@Override
				public void accept(BatchJob batchJob, Object status) {
					batchJob.setStatus((String)status);
				}

			});
		attributeGetterFunctions.put(
			"callbackURL",
			new Function<BatchJob, Object>() {

				@Override
				public Object apply(BatchJob batchJob) {
					return batchJob.getCallbackURL();
				}

			});
		attributeSetterBiConsumers.put(
			"callbackURL",
			new BiConsumer<BatchJob, Object>() {

				@Override
				public void accept(BatchJob batchJob, Object callbackURL) {
					batchJob.setCallbackURL((String)callbackURL);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getBatchJobId() {
		return _batchJobId;
	}

	@Override
	public void setBatchJobId(long batchJobId) {
		_batchJobId = batchJobId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getKey() {
		if (_key == null) {
			return "";
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		_columnBitmask |= KEY_COLUMN_BITMASK;

		if (_originalKey == null) {
			_originalKey = _key;
		}

		_key = key;
	}

	public String getOriginalKey() {
		return GetterUtil.getString(_originalKey);
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public Date getStartTime() {
		return _startTime;
	}

	@Override
	public void setStartTime(Date startTime) {
		_startTime = startTime;
	}

	@JSON
	@Override
	public Date getEndTime() {
		return _endTime;
	}

	@Override
	public void setEndTime(Date endTime) {
		_endTime = endTime;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@JSON
	@Override
	public String getCallbackURL() {
		if (_callbackURL == null) {
			return "";
		}
		else {
			return _callbackURL;
		}
	}

	@Override
	public void setCallbackURL(String callbackURL) {
		_callbackURL = callbackURL;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, BatchJob.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BatchJob toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BatchJob)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BatchJobImpl batchJobImpl = new BatchJobImpl();

		batchJobImpl.setBatchJobId(getBatchJobId());
		batchJobImpl.setCreateDate(getCreateDate());
		batchJobImpl.setModifiedDate(getModifiedDate());
		batchJobImpl.setKey(getKey());
		batchJobImpl.setName(getName());
		batchJobImpl.setStartTime(getStartTime());
		batchJobImpl.setEndTime(getEndTime());
		batchJobImpl.setStatus(getStatus());
		batchJobImpl.setCallbackURL(getCallbackURL());

		batchJobImpl.resetOriginalValues();

		return batchJobImpl;
	}

	@Override
	public int compareTo(BatchJob batchJob) {
		long primaryKey = batchJob.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BatchJob)) {
			return false;
		}

		BatchJob batchJob = (BatchJob)obj;

		long primaryKey = batchJob.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		BatchJobModelImpl batchJobModelImpl = this;

		batchJobModelImpl._setModifiedDate = false;

		batchJobModelImpl._originalKey = batchJobModelImpl._key;

		batchJobModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BatchJob> toCacheModel() {
		BatchJobCacheModel batchJobCacheModel = new BatchJobCacheModel();

		batchJobCacheModel.batchJobId = getBatchJobId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			batchJobCacheModel.createDate = createDate.getTime();
		}
		else {
			batchJobCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			batchJobCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			batchJobCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		batchJobCacheModel.key = getKey();

		String key = batchJobCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			batchJobCacheModel.key = null;
		}

		batchJobCacheModel.name = getName();

		String name = batchJobCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			batchJobCacheModel.name = null;
		}

		Date startTime = getStartTime();

		if (startTime != null) {
			batchJobCacheModel.startTime = startTime.getTime();
		}
		else {
			batchJobCacheModel.startTime = Long.MIN_VALUE;
		}

		Date endTime = getEndTime();

		if (endTime != null) {
			batchJobCacheModel.endTime = endTime.getTime();
		}
		else {
			batchJobCacheModel.endTime = Long.MIN_VALUE;
		}

		batchJobCacheModel.status = getStatus();

		String status = batchJobCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			batchJobCacheModel.status = null;
		}

		batchJobCacheModel.callbackURL = getCallbackURL();

		String callbackURL = batchJobCacheModel.callbackURL;

		if ((callbackURL != null) && (callbackURL.length() == 0)) {
			batchJobCacheModel.callbackURL = null;
		}

		return batchJobCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BatchJob, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BatchJob, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BatchJob, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((BatchJob)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<BatchJob, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<BatchJob, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BatchJob, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((BatchJob)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		BatchJob.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		BatchJob.class, ModelWrapper.class
	};

	private long _batchJobId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _key;
	private String _originalKey;
	private String _name;
	private Date _startTime;
	private Date _endTime;
	private String _status;
	private String _callbackURL;
	private long _columnBitmask;
	private BatchJob _escapedModel;

}